version: '3'
services:
  worker-1:
    build:
      context: /worker-1
      dockerfile: Dockerfile
    volumes:
      - .\data:/var/data
      - .\result:/var/result

  worker-2:
    depends_on:
      - worker-1
    build:
      context: /worker-2
      dockerfile: Dockerfile
    volumes:
      - .\result:/var/data
      - .\result:/var/result